version: '3.5'
services:
  qteste_app:
        image: ${REGISTRY_URL}/qteste_app:frakenphp
        env_file:
            - .env
        deploy:
          labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.docker.network=traefik-public
            - traefik.constraint-label=traefik-public
            - traefik.http.routers.qteste-http.rule=Host(`${APP_URL:-localhost}`)
            - traefik.http.routers.qteste-http.entrypoints=http
            - traefik.http.routers.qteste-http.middlewares=https-redirect
            - traefik.http.routers.qteste-https.rule=Host(`${APP_URL:-localhost}`)
            - traefik.http.routers.qteste-https.entrypoints=https
            - traefik.http.routers.qteste-https.tls=true
            - traefik.http.routers.qteste-https.tls.certresolver=le
            - traefik.http.services.qteste.loadbalancer.server.port=80
        restart: always
        ports:
          - ${PORT}:80
        networks:
          - traefik-public
  qteste_scheduler:
        image: ${REGISTRY_URL}/qteste_app:frakenphp
        env_file:
            - .env
        depends_on:
            - qteste_app
        environment:
            - CONTAINER_ROLE=scheduler
            - USERID=${USERID:-1001}
        networks:
            - traefik-public
  qteste_queue:
        image: ${REGISTRY_URL}/qteste_app:frakenphp
        env_file:
            - .env
        depends_on:
            - qteste_app
        environment:
            - CONTAINER_ROLE=queue
            - USERID=${USERID:-1001}
        networks:
            - traefik-public

networks:
    traefik-public:
        external: true
volumes:
    redisdata:
        driver: local
