version: '3.5'
services:
  qteste_app:
        image: ${REGISTRY_URL}/qteste_app:2.0
        env_file:
            - .env
        deploy:
          labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.docker.network=traefik-public
            - traefik.constraint-label=traefik-public
            - traefik.http.routers.${CONTAINER_NAME:-qteste}-http.rule=Host(`${APP_URL:-localhost}`)
            - traefik.http.routers.${CONTAINER_NAME:-qteste}-http.entrypoints=http
            - traefik.http.routers.${CONTAINER_NAME:-qteste}-http.middlewares=https-redirect
            - traefik.http.routers.${CONTAINER_NAME:-qteste}-https.rule=Host(`${APP_URL:-localhost}`)
            - traefik.http.routers.${CONTAINER_NAME:-qteste}-https.entrypoints=https
            - traefik.http.routers.${CONTAINER_NAME:-qteste}-https.tls=true
            - traefik.http.routers.${CONTAINER_NAME:-qteste}-https.tls.certresolver=le
            - traefik.http.services.${CONTAINER_NAME:-qteste}.loadbalancer.server.port=80
        restart: always
        entrypoint: ["/app/docker/entrypoint.sh"]
        ports:
          - ${PORT}:80
        networks:
          - traefik-public
  qteste_scheduler:
        image: ${REGISTRY_URL}/qteste_app:2.0
        env_file:
            - .env
        depends_on:
            - qteste_app
        entrypoint: ["/app/docker/entrypoint.sh"]
        environment:
            - CONTAINER_ROLE=scheduler
            - USERID=${USERID:-1001}
        networks:
            - traefik-public
  qteste_queue:
        image: ${REGISTRY_URL}/qteste_app:2.0
        env_file:
            - .env
        depends_on:
            - qteste_app
        entrypoint: ["/app/docker/entrypoint.sh"]
        environment:
            - CONTAINER_ROLE=queue
            - USERID=${USERID:-1001}
        networks:
            - traefik-public

networks:
    traefik-public:
        external: true
volumes:
    redisdata:
        driver: local
