version: '3.5'
services:
    qteste_app:
        image: qteste_app:2.0
        build:
            context: ./
            dockerfile: docker/production/Dockerfile
            args:
                - "BUILD_APP_ENV=${APP_ENV}"
        restart: always
        entrypoint: ["/app/docker/entrypoint.sh"]
        env_file:
            - .env
        volumes:
            -   ./:/app
        ports:
            - ${PORT}:80
            - "2019:2019"
        networks:
            - traefik-public
    qteste_scheduler:
        image: qteste_app:2.0
        container_name: ${APP_NAME}_scheduler
        restart: unless-stopped
        entrypoint:
            - ./docker/entrypoint.sh
        env_file:
            - .env
        depends_on:
            - qteste_app
        environment:
            - CONTAINER_ROLE=scheduler
            - USERID=${USERID:-1001}
        networks:
            - traefik-public
    qteste_queue:
        image: qteste_app:2.0
        container_name: ${APP_NAME}_queue
        restart: unless-stopped
        entrypoint:
            - ./docker/entrypoint.sh
        env_file:
            - .env
        depends_on:
            - qteste_app
        environment:
            - CONTAINER_ROLE=queue
            - USERID=${USERID:-1001}
        networks:
            - traefik-public
networks:
    traefik-public:
        external: true
volumes:
    redisdata:
        driver: local
