version: '3.5'
services:
    qakit_app:
        image: qakit_app
        container_name: ${APP_NAME}_app
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/Dockerfile
            args:
                - "BUILD_APP_ENV=${APP_ENV}"
        env_file:
            - .env
        environment:
            - CONTAINER_ROLE=app
            - USERID=${USERID:-1001}
        healthcheck:
            test: php -i || exit 1
            interval: 30s
            retries: 5
            start_period: 30s
            timeout: 10s
        networks:
            - traefik-public
    qakit_scheduler:
        image: qakit_app
        container_name: ${APP_NAME}_scheduler
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - qakit_app
        environment:
            - CONTAINER_ROLE=scheduler
            - USERID=${USERID:-1001}
        networks:
            - traefik-public
    qakit_queue:
        image: qakit_app
        container_name: ${APP_NAME}_queue
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - qakit_app
        environment:
            - CONTAINER_ROLE=queue
            - USERID=${USERID:-1001}
        networks:
            - traefik-public
    qakit_nginx:
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        image: qakit_nginx
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        environment:
            - APP_NAME=${APP_NAME}
        env_file:
            - .env
        deploy:
            labels:
                - traefik.enable=true
                - traefik.port=80
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.qakit-http.rule=Host(`${APP_URL:-localhost}`)
                - traefik.http.routers.qakit-http.entrypoints=http
                - traefik.http.routers.qakit-http.middlewares=https-redirect
                - traefik.http.routers.qakit-https.rule=Host(`${APP_URL:-localhost}`)
                - traefik.http.routers.qakit-https.entrypoints=https
                - traefik.http.routers.qakit-https.tls=true
                - traefik.http.routers.qakit-https.tls.certresolver=le
                - traefik.http.services.qakit.loadbalancer.server.port=80
            replicas: ${NGINX_REPLICAS:-1}
        depends_on:
            - qakit_app
        healthcheck:
            test: nginx -t || exit 1
            interval: 20s
            retries: 10
            start_period: 30s
            timeout: 10s
        ports:
            - ${PORT}:80
        networks:
            - traefik-public
networks:
    traefik-public:
        external: true
volumes:
    redisdata:
        driver: local
