export enum PermissionEnum {
    VER_CHECKPOINT = 'VER_CHECKPOINT',
    CRIAR_CHECKPOINT = 'CRIAR_CHECKPOINT',
    EDITAR_CHECKPOINT = 'EDITAR_CHECKPOINT',
    EXCLUIR_CHECKPOINT = 'EXCLUIR_CHECKPOINT'

}
