export enum PermissionEnum {
    LISTAR_OBSERVACAO = 'LISTAR_OBSERVACAO',
    INSERIR_OBSERVACAO = 'INSERIR_OBSERVACAO',
    ALTERAR_OBSERVACAO = 'ALTERAR_OBSERVACAO',
    REMOVER_OBSERVACAO = 'REMOVER_OBSERVACAO'

}
