<?php

namespace App\System\Enums;

enum PermissionEnum:string
{
    // System permissions
    case LISTAR_USUARIO = 'LISTAR_USUARIO';
    case ALTERAR_USUARIO = 'ALTERAR_USUARIO';
    case REMOVER_USUARIO = 'REMOVER_USUARIO';
    case INSERIR_USUARIO = 'INSERIR_USUARIO';

    case ALTERAR_SENHA_USUARIO = 'ALTERAR_SENHA_USUARIO';
    case LISTAR_EQUIPE = 'LISTAR_EQUIPE';
    case INSERIR_EQUIPE = 'INSERIR_EQUIPE';
    case ALTERAR_EQUIPE = 'ALTERAR_EQUIPE';
    case REMOVER_EQUIPE = 'REMOVER_EQUIPE';
    case VINCULAR_EQUIPE = 'VINCULAR_EQUIPE';
    case ALTERAR_EMPRESA = 'ALTERAR_EMPRESA';
}
