<?php

namespace App\System\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Equipe  extends Model
{
    use HasFactory, SoftDeletes;
    protected $table = 'equipes';

    protected $fillable = [
        'id',
        'nome',
        'empresa_id'
    ];
    protected static function boot()
    {
        static::creating(function ($model) {
            $model->empresa_id = auth()->user()->empresa_id;
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }


    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'users_equipes');
    }
    public function empresa()
    {
        return $this->belongsTo(Empresa::class);
    }
    public function newQuery()
    {
        return parent::newQuery()->where('empresa_id', Auth::user()->empresa_id);
    }
}
