export enum PermissionEnum {
    LISTAR_RETRABALHO = 'LISTAR_RETRABALHO',
    INSERIR_RETRABALHO = 'INSERIR_RETRABALHO',
    ALTERAR_RETRABALHO = 'ALTERAR_RETRABALHO',
    REMOVER_RETRABALHO = 'REMOVER_RETRABALHO',
    VER_TODOS_RETRABALHOS = 'VER_TODOS_RETRABALHOS',
    ALTERAR_TODOS_RETRABALHOS = 'ALTERAR_TODOS_RETRABALHOS',
    REMOVER_TODOS_RETRABALHOS = 'REMOVER_TODOS_RETRABALHOS',
    LISTAR_MEUS_RETRABALHOS = 'LISTAR_MEUS_RETRABALHOS',
    VER_DASHBOARD = 'VER_DASHBOARD',
    VER_RELATORIO_DESENVOLVEDOR = 'VER_RELATORIO_DESENVOLVEDOR',
    VER_RELATORIO_GESTOR = 'VER_RELATORIO_GESTOR',
    VER_RELATORIO_AUDITOR = 'VER_RELATORIO_AUDITOR'


}
