export enum PermissionEnum {
    VER_ALOCACAO = 'VER_ALOCACAO',
    CRIAR_ALOCACAO = 'CRIAR_ALOCACAO',
    EDITAR_ALOCACAO = 'EDITAR_ALOCACAO',
    EXCLUIR_ALOCACAO = 'EXCLUIR_ALOCACAO',
    VER_MINHA_ALOCACAO = 'VER_MINHA_ALOCACAO',
    CONCLUIR_ALOCACAO = 'CONCLUIR_ALOCACAO'

}
