<?php

namespace App\Modules\Retrabalhos\Enums;

enum PermissionEnum:string
{
   case LISTAR_RETRABALHO = 'LISTAR_RETRABALHO';
    case INSERIR_RETRABALHO = 'INSERIR_RETRABALHO';
    case ALTERAR_RETRABALHO = 'ALTERAR_RETRABALHO';
    case REMOVER_RETRABALHO = 'REMOVER_RETRABALHO';
    case VER_TODOS_RETRABALHOS = 'VER_TODOS_RETRABALHOS';
    case ALTERAR_TODOS_RETRABALHOS = 'ALTERAR_TODOS_RETRABALHOS';
    case REMOVER_TODOS_RETRABALHOS = 'REMOVER_TODOS_RETRABALHOS';

    case VER_DASHBOARD = 'VER_DASHBOARD';

}
